# Site settings
name: 王宁的博客
email: 1878708493@qq.com
author: 王宁
url: http://www.wangning1995.com
#resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/1878708493/
baseurl: ""
description: 宅又非宅的技术又非技术男
#meta_description: 王宁;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
#banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10
gems: [jekyll-paginate]
highlighter: pygments
highlight: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: 1878708493

# Build settings
markdown: kramdown

FB:
  comments :
    provider : youyan