# Site settings
name: WN 的博客
email: system2wn@163.com
author: system2wn
url: http://www.wangning1995.top
#resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/system2wn/
baseurl: "/LessOrMore"
description: 放开我，我还可以学!!
#meta_description: 王宁;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
#banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10
gems: [jekyll-paginate]
highlighter: rouge
highlight: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: system2wn

# Build settings
markdown: kramdown

FB:
  comments :
    provider : youyan